version: '3.8'

services:
  llm-frontend:
    build:
      context: ./llm-frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - ROUTER_URL=http://llm-backend:8080
    depends_on:
      - llm-backend
    networks:
      - llm-network

  llm-backend:
    build:
      context: ./llm-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge

volumes:
  model-data:
    driver: local 