version: '3'
services:

  server:
    image: rancher/k3s:v1.31.5-k3s1
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=token
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - ./output:/output  # get the kubeconfig file
    ports:
    - "6443:6443"  # Kubernetes API Server
    - "80:80"      # Ingress controller port 80
    - "443:443"    # Ingress controller port 443
    - "32001:32001"
    - "32002:32002"
    - "32003:32003"
    - "32004:32004"
    - "32005:32005"

  agent:
    image: rancher/k3s:v1.31.5-k3s1
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=token

volumes:
  k3s-server: {}
