apiVersion: v1
kind: Service
metadata:
  name: llm-frontend
  namespace: llm
spec:
  type: NodePort
  selector:
    app: llm-frontend
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 32002